logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
      mongodb:
        driver: DEBUG
spring:
  application:
    name: shawarma
  thymeleaf:
    cache: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: admin