spring:
  application:
    name: shawarma
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:h2:mem:shawarma
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: shawarma
    username: sa
    password: