#logging:
#  level:
#    org:
#      springframework:
#        web: debug


spring:
#  main:
#    debug: true
  application:
    name: shawarma
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/ShawarmaDB
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: shawarma
    username: sa
    password:
    initialization-mode: always