services:
  activemq:
    image: rmohr/activemq
    container_name: shawarma-activemq-devx
    network_mode: host
#    ports:
#      - 8161:8161
#      - 61616:61616
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=evgen
      - ACTIVEMQ_ADMIN_PASSWORD=evgen
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    restart: always
