server:
  port: 8081

spring:
  application:
    name: shawarma
  thymeleaf:
    cache: true
  jms:
    template:
      receive-timeout: 2
      default-destination: shawarmaQueue
  activemq:
    broker-url: tcp://localhost:61616
    user: evgen
    password: evgen