server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/OAuth2DB
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: shawarma
    username: sa
    password:
    initialization-mode: always